# 基本情報
site_name: 'コジオン: チェス'
site_description: 'チェスの備忘録です。'
site_author: 'Hideyuki Kojima'
site_url: 'https://kojion.github.io/chess/'
copyright: 'Copyright © 2022 Hideyuki Kojima.'

# ナビゲーション
nav:
  - 雑記:
    - index.md
    - note/introduction.md
    - note/youtube.md
    - 2023 年:
      - note/20230308.md
      - note/20230125.md
    - 2022 年:
      - note/20221219.md
      - note/20221117.md
      - note/20220913.md
      - note/20220728.md
  - オープニング研究:
    - アンチ・ロンドン・システム:
        - opening/anti-london-system/001.md
  - 自戦記:
    - otb/2023/0610.md
    - otb/2022/1009.md
    - otb/2022/0723.md
    - otb/2022/0625.md
  - MkDocs:
    - mkdocs/001.md
    - mkdocs/002.md
    - mkdocs/003.md
    - mkdocs/004.md
    - mkdocs/005.md
    - mkdocs/006.md
    - mkdocs/007.md
    - mkdocs/008.md
    - mkdocs/009.md

# テーマ
theme:
  name: 'material'
  language: 'ja'
  logo: assets/logo.png
  favicon: assets/favicon.png
  custom_dir: overrides
  palette:
    primary: 'light blue'
    accent: 'orange'
  font:
    text: 'BIZ UDPGothic'
    code: 'JetBrains Mono'
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

# Google Analytics
extra:
  analytics:
    provider: google
    property: G-WE11TWYYEL
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/zbxah
      name: コジオン on Twitter
    - icon: fontawesome/brands/github
      link: https://github.com/kojion/chess
      name: GitHub Repository
    - icon: fontawesome/solid/paper-plane
      link: mailto:kojionilk@gmail.com
      name: Email to Kojion

# 拡張 CSS
extra_css:
  - assets/extra.css

# 拡張 JavaScript
extra_javascript:
  - assets/extra.js

# プラグイン
plugins:
  - search:
      lang: ja
  - glightbox

# マークダウン拡張
markdown_extensions:
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - meta
