site_name: 'コジオン: チェス'
site_description: 'チェスの備忘録です。'
site_author: 'Hideyuki Kojima'
site_url: 'https://kojion.github.io/chess/'
copyright: 'Copyright © 2022 Hideyuki Kojima.'

theme:
  name: 'material'
  language: 'ja'
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    primary: 'light blue'
    accent: 'orange'
  font:
    text: 'BIZ UDPGothic'
    code: 'JetBrains Mono'
  features:
    - navigation.tabs
    - navigation.top
    - toc.integrate

extra_css:
  - assets/extra.css

extra_javascript:
  - assets/extra.js

plugins:
  - search:
      lang: ja
  - glightbox

markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
