# 基本情報
site_name: 'コジオン: チェス'
site_description: 'チェスの備忘録です。'
site_author: 'Hideyuki Kojima'
site_url: 'https://kojion.github.io/chess/'
copyright: 'Copyright © 2022 Hideyuki Kojima.'

# ナビゲーション
nav:
  - index.md
  - MkDocs:
    - mkdocs/001.md
    - mkdocs/002.md
    - mkdocs/003.md
    - mkdocs/004.md
    - mkdocs/005.md
    - mkdocs/006.md

# テーマ
theme:
  name: 'material'
  language: 'ja'
  logo: assets/logo.png
  favicon: assets/favicon.png
  custom_dir: overrides
  palette:
    primary: 'light blue'
    accent: 'orange'
  font:
    text: 'BIZ UDPGothic'
    code: 'JetBrains Mono'
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - toc.integrate

# Google Analytics
extra:
  analytics:
    provider: google
    property: G-324152304

# 拡張 CSS
extra_css:
  - assets/extra.css

# 拡張 JavaScript
extra_javascript:
  - assets/extra.js

# プラグイン
plugins:
  - search:
      lang: ja
  - glightbox

# マークダウン拡張
markdown_extensions:
  - admonition
  - footnotes
  - codehilite
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - meta
